version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: web321
      POSTGRES_DB: web3
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data
