version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./tmp/redis:/data
